version: '3'
services:
  ssl_domain_expiry_check:
    container_name: ssl_certificate_expiry_check
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: 'America/Los_Angeles'
    volumes:
      - ./app:/srv/app:rw
    #environment:
    #  TZ: 'America/Los_Angeles'
