version: '3'
services:
  ssl_domain_expiry_check:
    container_name: ssl_certificate_expiry_check
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      - ./app:/srv/app:rw
    env_file:
      - .env
