ruby '2.7.8'

source 'http://rubygems.org'

gem 'slack-notifier', '~> 2.4'
gem 'ssl_expiry', '~> 1.0', '>= 1.0.3'
gem 'whenever', '~> 1.0.0'
gem 'net-http-persistent', '~> 3.1.0'
gem 'connection_pool', '2.2.2'
gem 'openssl', '2.1.2'
